# https://docs.github.com/en/actions/using-workflows/about-workflows
name: learn-github-actions
run-name: testing run
on: [push]
jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
        # выкачиваем репозиторий
      - uses: actions/checkout@v3
        # настраиваем java (https://github.com/actions/setup-java)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # https://github.com/Xotabu4/selenoid-github-action
      - name: Start selenoid
        uses: Xotabu4/selenoid-github-action@v2
        # запускаем тесты с Селеноидом
      - run: chmod +x ./gradlew
      - run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub